customers/urls.py
from django.urls import path

from .views import (CustomerCreateView, CustomerDetailsView, CustomersListView,
                    CustomerUpdateView, StoreCreateView, StoreDetailsView,
                    StoreProductExcelUploadView, StoresListView,
                    StoreUpdateView)

app_name = 'customers'

urlpatterns = [
    path('', CustomersListView.as_view(), name='list'),
    # path('add/', CustomerCreateView.as_view(), name='add'),
    path('create-customer/', CustomerCreateView.as_view(), name='create-customer'),
    path('view-customer/<int:pk>/', CustomerDetailsView.as_view(), name='view-customer'),
    path('update-customer/<int:pk>/', CustomerUpdateView.as_view(), name='update-customer'),


    path('stores/', StoresListView.as_view(), name='stores_list'),
    path('create-store/', StoreCreateView.as_view(), name='stores_create'),
    path('view-store/<int:pk>/', StoreDetailsView.as_view(), name='stores_view'),
    path('update-store/<int:pk>/', StoreUpdateView.as_view(), name='stores_update'),
    path('upload-products/<int:store_id>/', StoreProductExcelUploadView.as_view(), name='upload_products'),



    # path('delete/<int:pk>/', views.CustomerDeleteView.as_view(), name='delete'),
    # path('detail/<int:pk>/', views.CustomerDetailView.as_view(), name='detail'),

]

ecom_cms/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("customers/", include("customers.urls")),
    path("products/", include("products.urls")),
] + debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path

from .views import ProductsListView, productDetails

app_name = 'products'


urlpatterns = [

  path('details/<int:product_id>/', productDetails, name='product-details'),
  path('list/', ProductsListView.as_view(), name='products-list'),
  
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
  path("", views.StartingPageView.as_view(), name='starting-page'),
  path('login/', views.CustomLoginFormView.as_view(), name='login'),
  path('logout/', views.CustomLogoutView.as_view(), name='logout'),
  path('register/', views.UserRegistrationView.as_view(), name='register'),

  path('users/', views.UserListView.as_view(), name='list'),
  path('home/', views.HomePageView.as_view(), name='home'),
  path('users/update-profile/<int:pk>/', views.UserProfileUpdateView.as_view(), name='update-profile'),
  path('users/update-password/<int:pk>/', views.AdminPasswordUpdateView.as_view(), name='update-password'),
  path('users/delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete-user'),

]

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ECOM CMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Hi {{ request.user.username }}
              </a>
              <ul class="dropdown-menu">
                {% if request.user.is_superuser %}
                  <li><a class="dropdown-item" href="{% url "users:list" %}">Users</a></li>
                  <li><a class="dropdown-item" href="{% url "customers:list" %}">Customers</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url "customers:stores_list" %}">Stores</a></li>
                <li><a class="dropdown-item" href="{% url "products:products-list" %}">Products</a></li>
                {% comment %} 
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                {% endcomment %}
              </ul>
            </li>
            {% comment %} 
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'list' %}active{% endif %}" href="{% url 'users:list' %}">Users</a>
              <a class="nav-link {% if 'users' in request.path %}active{% endif %}" href="{% url 'users:list' %}">Users</a>
            </li>
            {% endcomment %}
            <li class="nav-item" style="align-self: center;">
              <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="nav-link btn btn-link p-0 border-0">
                  Logout
                </button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'users:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>